### 회원가입
POST http://localhost:8080/api/member/signup
Content-Type: application/json

{
  "name" : "name",
  "password" : "test1234"
}

### 회원가입2
POST http://localhost:8080/api/member/signup
Content-Type: application/json

{
  "name" : "name2",
  "password" : "test1234"
}

### 로그인
POST http://localhost:8080/api/member/login
Content-Type: application/json

{
  "name" : "name",
  "password" : "test1234"
}

### 로그인 - 네임 오류
POST http://localhost:8080/api/member/login
Content-Type: application/json

{
  "name" : "namee",
  "password" : "test1234"
}

### 로그인 - 패스워드 오류
POST http://localhost:8080/api/member/login
Content-Type: application/json

{
  "name" : "name",
  "password" : "test12"
}