spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2.console.enabled: true

  jpa:
    hibernate:
      ddl-auto: create # 실행 시점에 테이블을 매번 생성 (이전 테이블 삭제)
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  messages:
    basename: i18n/exception
    encoding: utf-8

    jwt:
      secret: test2345

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type: trace # 파라미터에 대한 로그를 찍어줌